LTO_ENABLE = yes

AUDIO_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
COMMAND_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = yes
MOUSEKEY_ENABLE = yes
MIDI_ENABLE = no
MUSIC_ENABLE = no
NKRO_ENABLE = no
TAP_DANCE_ENABLE = no # need to implement the handler function for this to work
UNICODE_COMMON = yes
UNICODE_ENABLE = yes
UNICODE_MAP_ENABLE = yes
