#pragma once

#define LAYER_STATE_8BIT // we don't need more than 8 layers
// Tap-and-hold settings
#define CHORDAL_HOLD
// #define HOLD_ON_OTHER_KEY_PRESS // alternative: PERMISSIVE_HOLD
#define PERMISSIVE_HOLD // alternative: HOLD_ON_OTHER_KEY_PRESS
#define PERMISSIVE_HOLD_PER_KEY
#define TAPPING_TERM 150 // default is 200
#define TAPPING_TERM_PER_KEY
#define USB_POLLING_INTERVAL_MS 5 // maybe this makes things work on the nature board with
#define FLOW_TAP_TERM 150

// Caps word
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

// Lights, https://docs.qmk.fm/#/feature_rgb_matrix?id=rgb-matrix-effects
#define RGBLIGHT_LAYERS 2 // default is 8
#define RGB_MATRIX_DEFAULT_ON false
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_NONE

#define L2_ESC LT(2, KC_ESC)
// #define C_2TAB LT(2, KC_TAB)
#define L3_ESC LT(3, KC_ESC) // mouse via ESC
#define L3_TAB LT(3, KC_TAB) // mouse via TAB
#define L5_V LT(5, KC_V)

#define C_CTLes LCTL_T(KC_ESC)

// home row
#define C_GUIA LGUI_T(KC_A)
#define C_ALTS LALT_T(KC_S)
#define C_SFTD LSFT_T(KC_D)
#define C_CTLF LCTL_T(KC_F)
#define C_CTLJ RCTL_T(KC_J)
#define C_SFTK RSFT_T(KC_K)
#define C_ALTL LALT_T(KC_L)
#define C_GUIsc RGUI_T(KC_SCLN)

// Danish characters
#define DK_AE UP(AE_LOWER, AE_UPPER)
#define DK_OE UP(AE_LOWER, AE_UPPER)
#define DK_AA UP(AE_LOWER, AE_UPPER)

#define ___ KC_TRNS
#define _x_ KC_NO

// Everything below this is not used and thus disabled to save space

// RGB light
#undef RGBLIGHT_ANIMATIONS
#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_EFFECT_TWINKLE

// RGB matrix light
#undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_BREATHING
#undef ENABLE_RGB_MATRIX_BAND_SAT
#undef ENABLE_RGB_MATRIX_BAND_VAL
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#undef ENABLE_RGB_MATRIX_CYCLE_ALL
#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#undef ENABLE_RGB_MATRIX_DUAL_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#undef ENABLE_RGB_MATRIX_FLOWER_BLOOMING
#undef ENABLE_RGB_MATRIX_RAINDROPS
#undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#undef ENABLE_RGB_MATRIX_HUE_BREATHING
#undef ENABLE_RGB_MATRIX_HUE_PENDULUM
#undef ENABLE_RGB_MATRIX_HUE_WAVE
#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#undef ENABLE_RGB_MATRIX_PIXEL_FLOW
#undef ENABLE_RGB_MATRIX_PIXEL_RAIN

#undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#undef ENABLE_RGB_MATRIX_DIGITAL_RAIN

#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#undef ENABLE_RGB_MATRIX_SPLASH
#undef ENABLE_RGB_MATRIX_MULTISPLASH
#undef ENABLE_RGB_MATRIX_SOLID_SPLASH
#undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

// I don't have Cherry MX Lock switches
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define NO_MUSIC_MODE
