#if __has_include("keymap.h")
#include "keymap.h"
#endif

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_BASE] = LAYOUT(
        KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_EQL, KC_MINS, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, L3_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_LBRC, KC_RBRC, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, L2_ESC, C_GUIA, C_ALTS, C_SFTD, C_CTLF, KC_G, KC_BSPC, KC_ENT, KC_H, C_CTLJ, C_SFTK, C_ALTL, C_GUIsc, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, L5_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_LCTL, KC_LGUI, SC_LAPO, C_CTLes, KC_ESC, KC_SPC, KC_ENT, KC_DEL, SC_RAPC, _T_WIN, KC_PGUP, KC_PGDN, KC_SPC, KC_LGUI, KC_ESC, KC_RALT, KC_RCTL, KC_SPC
    ),
    [_ARROWS] = LAYOUT(
        KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F11, KC_F12, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, EE_CLR, ___, ___, ___, ___, ___, ___, NK_TOGG, KC_PSCR, ___, KC_HOME, KC_UP, KC_PGUP, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, KC_LEFT, KC_DOWN, KC_RGHT, ___, ___, ___, ___, ___, ___, ___, ___, ___, KC_END, ___, KC_PGDN, ___, KC_MUTE, ___, ___, ___, C_QMKV, ___, ___, ___, ___, ___, _T_BAS, KC_VOLU, KC_MNXT, ___, ___, ___, KC_MPLY, KC_VOLD, KC_MPRV
    ),
    [_DANISH] = LAYOUT(
        ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, KC_BSPC, ___, ___, ___, DK_AE, ___, ___, ___, ___, ___, ___, ___, DK_OE, ___, KC_BSLS, ___, DK_AA, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, KC_ENT, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, KC_RSFT, ___, ___, ___, KC_SPC, ___, KC_LCTL, KC_RSFT, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___
    ),
    [_MOUSE] = LAYOUT(
        ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, MS_BTN1, MS_UP, MS_BTN2, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, MS_LEFT, MS_DOWN, MS_RGHT, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___
    ),
    [_NUMBERS] = LAYOUT(
        KC_TAB, _x_, _x_, _x_, _x_, _x_, _x_, KC_PSLS, KC_P7, KC_P8, KC_P9, KC_PPLS, _x_, _x_, KC_TAB, _x_, _x_, _x_, _x_, _x_, _x_, KC_PAST, KC_P4, KC_P5, KC_P6, KC_PCMM, _x_, _x_, KC_TAB, _x_, _x_, _x_, _x_, _x_, _x_, KC_PMNS, KC_P1, KC_P2, KC_P3, KC_PEQL, _x_, _x_, KC_TAB, _x_, _x_, _x_, _x_, _x_, _x_, KC_P0, _x_, KC_PDOT, KC_PENT, _x_, KC_TAB, _x_, _x_, _x_, _x_, _x_, _x_, _x_, _x_, ___, _x_, _x_, _x_, _x_, _x_, _x_, _x_, _x_
    ),
    [_WINDOWS] = LAYOUT(
        ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, KC_BSPC, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, KC_BSLS, KC_LCTL, KC_A, KC_S, KC_D, KC_F, ___, ___, ___, ___, KC_J, KC_K, KC_L, ___, KC_ENT, ___, ___, ___, ___, KC_V, ___, ___, ___, ___, ___, ___, KC_RSFT, KC_CAPS, ___, ___, KC_SPC, ___, KC_LCTL, KC_RSFT, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___
    )};

#ifdef OTHER_KEYMAP_C
#include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

